# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-21 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20161016_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedtorrents',
            name='startSeedingTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
